security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\Participant:
            algorithm: argon2i
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Participant
                property: email
        app_user_admin:
            memory:
                users:
                    admin: { password: 'admin', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            http_basic:
                realm: Zone admin
            provider: app_user_admin
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            form_login: true
            provider: app_user_provider
            logout:
                path: app_logout
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/(?!login|register), roles: ROLE_USER }
#         - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
